### ISSUE TITLE
carnival theme: figures & images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1081]
<img width="377" alt="Screen Shot 2019-05-20 at 6 59 23 PM" src="https://user-images.githubusercontent.com/11299125/58059174-6931dc00-7b31-11e9-92aa-42578a47bb1c.png">

The following alignment rule and treatment for unnumbered classes should be library wide standard:
numbered `<figure>`  with title: centered
numbered  `<figure>` with title and caption: centered
unnumbered `<figure>`  (`unnumbered` class with `<label/>`): centered
images `<image>` (no caption/figure number): left aligned

The following are specific to carnival theme
Caption font: IBM Plex Sans; 1.2rem
Figure number: Muli bold; 1.2rem;  color: match header colors in book specific levels? (in screenshot it's #C31427)
Figure title: Muli bold; 1.2rem
Padding between picture and caption stuff: 1rem

**Comment by openstaxalina** [comment]
@brittany-johnson confirming status with Richelle.

**Comment by richelleyy** [comment]
Common Figures:
<img width="616" alt="Screen Shot 2019-07-19 at 9 48 33 AM" src="https://user-images.githubusercontent.com/50836449/61544898-ef707e80-aa0b-11e9-945b-27d342dd775b.png">

Carnival Theme:
<img width="937" alt="Screen Shot 2019-07-19 at 9 46 02 AM" src="https://user-images.githubusercontent.com/50836449/61544912-f5fef600-aa0b-11e9-8c2b-e21b1fd98556.png">

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8dc8bb1e-5f2c-43fb-b3f8-f16069a2431b)

- Figure number not styled
- Figure number is in IBM Sans instead of Muli bold

**Comment by richelleyy** [comment]
@Stackblocks Here's what I have on the pdf. I'm not sure why the figure number is '3.9' on mine and '1.2' on yours. Are we using the same book? The one I'm using is chemistry.
<img width="970" alt="Screen Shot 2019-07-26 at 10 33 11 AM" src="https://user-images.githubusercontent.com/50836449/61963574-8cde2c00-af91-11e9-8de7-96dbf2e24227.png">

**Comment by Stackblocks** [comment]
I was looking in Anatomy & Physiology, but since this should be a library-wide standard per Larissa's initial comment it should be the same across books. I'll check Chemistry now to make sure it's implemented correctly there.

**Comment by Stackblocks** [comment]
Seeing the styling in Chemistry so that is good, but the title font is `muli black` instead of `muli bold`, and this should be library-wide standard. We may end up breaking this into multiple issues if it has to be implemented book-by-book.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cff0249d-d727-4b79-8f9a-9271ce4e665a)

**Comment by richelleyy** [comment]
@Stackblocks I created another PR and hopefully the font issue should be fixed right now :) 
<img width="1039" alt="Screen Shot 2019-07-26 at 12 42 40 PM" src="https://user-images.githubusercontent.com/50836449/61970795-1ea26500-afa3-11e9-93c7-44fb2ab9e12d.png">

**Comment by Stackblocks** [comment]
Still getting muli black instead of muli bold on figure titles with updated code / content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c413957b-44f1-43ea-949e-ef3c4fbea138)

**Comment by brittweinstein** [comment]
@richelleyy please take a look at this

**Comment by Stackblocks** [comment]
We've swung too far in the other direction. Now instead of Muli Black we've shot over to Muli (Plain). 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0452b135-e6d4-4721-850d-382b7e9cd8be)

**Comment by Stackblocks** [comment]
THIS IS FINE PER @lwtchu

**Comment by Stackblocks** [comment]
Reopening for cleanup / review

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![2019-08-15_14-07-36.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/748ea4d5-560d-4aa5-bc8e-fc300c94d6a3)

![2019-08-15_14-07-06.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d921ce50-bc81-4d2e-a120-9f4b20228b86)
